### ISSUE TITLE
Infinite update loop

### ISSUE THREAD

**Issue by M0nk3yy** [mtvjr/background-volume#10]
After installing the mod, it updates every time I click update, but is always version 1.4.2.

![image](https://user-images.githubusercontent.com/66137312/185805181-8b2963d1-e71a-458f-8ea3-baacacadd9c5.png)

**Comment by mtvjr** [comment]
Thanks for the bug report. I've confirmed the issue and I'll try to have a fix out as soon as possible.

**Comment by mtvjr** [comment]
Fixed in 1.5.1.

Thanks again for finding and reporting the bug.
