### ISSUE TITLE
Foundry v10.286 Error

### ISSUE THREAD

**Issue by eritzie** [mtvjr/background-volume#11]
I just update my Foundry instance on Forge to v10.286 and when I load the Background-Volume module I see the following error in the console.

![image](https://user-images.githubusercontent.com/39166319/194283926-19032e5a-4dcc-4c9b-8373-7b922ff79e85.png)

**Comment by marcstraube** [comment]
Running Foundry v10.287 on a Linux server, I can't recreate this error.

**Comment by mtvjr** [comment]
Hi @GrumpyVader, thanks for the bug report. I'll need to wait until Tuesday before investigating further, but I would appreciate if you could answer the following questions:

1. Did you have a scene open when you encountered this error?
2. What version of Background-Volume do you have installed?
3. What other modules do you have installed?

**Comment by mtvjr** [comment]
I've identified that the issue occurs when the game is loaded without an active scene. It appears to only be a console log, with no other issues manifesting. Nonetheless, the issue has been fixed in [Version 1.5.3](https://github.com/mtvjr/background-volume/releases/tag/v1.5.3).
