### ISSUE TITLE
Support new manifest formatting

### ISSUE THREAD

**Issue by uniwars** [mtvjr/background-volume#12]
Hi, after updating to v11 I get the following error in the module setup page :

The module "background-volume" is using "name" which is deprecated in favor of "id"
The module "background-volume" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object

**Comment by mtvjr** [comment]
Hi Uniwars,

Thanks for this report. I've intentionally used the old version in order to maintain backwards compatibility with the previous systems. When Foundry v12 arrives with dropped old-manifest support, I'll modify the module to remove backwards compatibility.

Hope this helps!

**Comment by mtvjr** [comment]
Fixed with Release 1.6.0
