### ISSUE TITLE
BUG - The module broke the scenes on version 0.7.1 of foundry #

### ISSUE THREAD

**Issue by p4535992** [mtvjr/background-volume#4]
**Environment Details:**

Foundry VTT Version: 0.7.1
Operating System: [Linux]
How Are You Using Foundry: [Linux,Native Application (Electron), Chrome]
Which Game System: Dungeons and Dragons 5th Edition, version 0.95
Modules Enabled?: yes
OS, Hosting, Browser (if applicable): Linux/Node/Chrome

**Description of the issue:**

It's a strange behaviour, after the module is enable, many of my scene have lost their customization settings.

There is no web console exception.

These are the steps for replicate the issue:

0) The module is disable at the start
1) Create a new scene
2) Select a new file for the background of the scene (in my use case it's a webm file)
3) Modify the background size scale from "1" to "2"
4) Save the scene
5) Refresh the page it's seem all good
6) Enable the module
7) Chage the "volume"
8) After the refresh the map settings it's going back to "1" not "2".

**Comment by p4535992** [comment]
It's seem some conflict with some other modules, not a bug on the module, i will look up on this.

**Comment by mtvjr** [comment]
Sorry for the late reply @p4535992, I've taken a bit of a break from Foundry & GitHub. Were you able to find any more information on the issue?

**Comment by p4535992** [comment]
No problem sir, ty for having the time for doing this project in the first place.
Yea it's more like a conflict with the alpha version 0.7.1 of Foundry, but until will not be a released version there is no need for a patch right now.
For now i just avoid scaling the scene and the module work just fine.

**Comment by mtvjr** [comment]
Thanks, I'll try to take a look tonight.

**Comment by mtvjr** [comment]
Sorry for the delay. I've tried looking into the issue on 0.7.2, but I do not see the "Background Size" option. I've tried adjusting the Grid Size, Initial View Position, and Padding Percentage options, but none of them are reset when I try to adjust the Background Volume setting.

Could you let me know if you are still facing this issue on 0.7.2 and if the "Background Size" option might be added by another module?
