### ISSUE TITLE
Players here sound briefly before it is muted

### ISSUE THREAD

**Issue by bryancasler** [mtvjr/background-volume#5]
I have a scene with a background video that has audio in it. I want to use my own audio and I muted it through Background Volume's settings on the scene. However when the scene loads, the players here the video's audio briefly before it is muted. It's only for a moment.

This might be an issue of just timing, and the order in which events happen on the page. If that's the case and it's being muted as fast as possible, then possibly an alternative approach might be to change up how background audio works when the module is installed. If possible, always start muted. And the unmute and set the volume to the the level selected. Not sure if that's even possible, just trying to help think outside th ebox.

**Comment by mtvjr** [comment]
Hi Bryan,

Thank you for submitting this report. Unfortunatly, I believe this is a technical limitation. When a scene loads, it's volume is first set by Foundry. Then, after Foundry has finished configuring the scene, my module is invoked and I make my changes to the volume. During the intial set up by foundry and during the invocation of any modules "updateScene" hooks before mine, the volume will be set to the "Ambient" volume setting.

I wish there was a way to prevent Foundry from setting the volume on scene load, but I don't believe that I can do such a thing. Your possible solutions are great ideas, but I don't believe I can get them working. I'm sorry that I have to close the issue without a solution.

**Comment by bryancasler** [comment]
Thanks @mtvjr I logged a request in the Foundry Discord Feature Request channel. Appreciate you taking the time to respond and all the hard work you put into this module.

REF: https://discordapp.com/channels/170995199584108546/517504137403826177/756687987206783048
